# Generated by Django 4.0.6 on 2022-07-30 22:01

import ProcessAdminRestApi.models.fields.XLSX_field
import ProcessAdminRestApi.models.upload_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmerge',
            name='calculate',
            field=ProcessAdminRestApi.models.upload_model.CalculateField(default=False),
        ),
        migrations.AddField(
            model_name='mailmerge',
            name='is_calculated',
            field=ProcessAdminRestApi.models.upload_model.IsCalculatedField(default=False),
        ),
        migrations.AlterField(
            model_name='mailmerge',
            name='upload_template',
            field=ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(upload_to=''),
        ),
    ]
