# Generated by Django 4.0.6 on 2022-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0003_alter_mail_docx_document_alter_mail_pdf_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='file_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mailmerge',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
