# Generated by Django 4.0.6 on 2022-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0006_alter_mail_docx_document_alter_mail_pdf_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mailmerge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
