# Generated by Django 4.0.6 on 2022-07-31 19:34

import ProcessAdminRestApi.models.fields.XLSX_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0007_alter_mail_id_alter_mailmerge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='docx_document',
            field=models.FileField(blank=True, default='', null=True, upload_to='submodels/MailMerge/docx_document/'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='pdf_document',
            field=models.FileField(blank=True, default='', null=True, upload_to='submodels/MailMerge/pdf_document/'),
        ),
        migrations.AlterField(
            model_name='mailmerge',
            name='upload_data',
            field=models.FileField(blank=True, default='', null=True, upload_to='submodels/MailMerge/upload_data/'),
        ),
        migrations.AlterField(
            model_name='mailmerge',
            name='upload_template',
            field=ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(blank=True, default='', null=True, upload_to='submodels/MailMerge/upload_template/'),
        ),
        migrations.AlterField(
            model_name='mailmerge',
            name='zip_docx',
            field=models.FileField(blank=True, default='', null=True, upload_to='submodels/MailMerge/zip_docx/'),
        ),
        migrations.AlterField(
            model_name='mailmerge',
            name='zip_pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='submodels/MailMerge/zip_docx/'),
        ),
    ]
