# Generated by Django 4.0.6 on 2022-12-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0009_alter_mail_docx_document_alter_mail_pdf_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationlog',
            name='frontendId',
            field=models.TextField(default='-1'),
        ),
        migrations.AddField(
            model_name='userchangelog',
            name='frontendId',
            field=models.TextField(default='-1'),
        ),
    ]
