# Generated by Django 4.0.6 on 2023-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0010_calculationlog_frontendid_userchangelog_frontendid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationlog',
            name='message_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
