# Generated by Django 4.1.13 on 2024-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0012_log_rename_frontendid_userchangelog_calculationid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='log',
            name='defining_fields_Log',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='filter',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='logfile_events',
            new_name='input_validation',
        ),
        migrations.RemoveField(
            model_name='log',
            name='logfile_timesheet',
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('group',), name='defining_fields_Log'),
        ),
    ]
